# Updated fly.toml for WebSocket support

app = "fauna-lmsh-timer"
primary_region = "ord"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[http_service.health_checks]
  type = "http"
  path = "/"  # or a specific health check endpoint if you have one
  grace_period = "30s"  # give more time to start up
  interval = "15s"
  timeout = "10s"
  restart_limit = 3  # allow more restart attempts

# Explicitly configure WebSocket support
[[services]]
  # http_checks = []
  internal_port = 8080
  # processes = ["app"]
  protocol = "tcp"
  
  # webSocket-specific configuration
  [services.websockets]
    enabled = true

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1